# Generated by Django 5.1 on 2024-08-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('imagem', models.ImageField(blank=True, upload_to='livraria/media')),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
