# Generated by Django 5.1 on 2024-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='livraria/pdfs'),
        ),
    ]
